/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//#define ADC_BASE_ADDR 0x50000000UL
//
//#define ADC_CRI_REG_OFFSET 0x08UL
//
//#define RCC_BASE_ADDR  0x40021000UL
//
//#define RCC_AHB_ENR_OFFSET 0x14UL
//
//#define RCC_AHB_ENR_ADDR (RCC_BASE_ADDR+RCC_AHB_ENR_OFFSET)
//
//#define ADC_CRI_REG_ADDR (ADC_BASE_ADDR + ADC_CRI_REG_OFFSET)
//
//int main(void)
//{
//    /* Loop forever */
//
//	uint32_t *pAdcCr1Reg=(uint32_t *)ADC_CRI_REG_ADDR;
//
//	uint32_t *pRccAhbEnr=(uint32_t *)RCC_AHB_ENR_ADDR;
//
//	//1. enable peripheral clock
//	*pRccAhbEnr |=(1<<28);
//	//2. modify ADC CR register
//
//	*pAdcCr1Reg |=(1<<28);
//	for(;;);
//}

#define ADC_BASE_ADDR      0x50000000UL
#define ADC_CR_OFFSET      0x08UL
#define RCC_BASE_ADDR      0x40021000UL
#define RCC_AHBENR_OFFSET  0x14UL

#define ADC_CR_ADDR        (ADC_BASE_ADDR + ADC_CR_OFFSET)
#define RCC_AHBENR_ADDR    (RCC_BASE_ADDR + RCC_AHBENR_OFFSET)

#define ADC_CR_DEEPPWD     (1U << 29)
#define ADC_CR_ADVREGEN_0  (1U << 28)

int main(void)
{
    volatile uint32_t *ADC_CR  = (volatile uint32_t *)ADC_CR_ADDR;
    volatile uint32_t *RCC_AHB = (volatile uint32_t *)RCC_AHBENR_ADDR;

    /* 1. Enable ADC clock */
    *RCC_AHB |= (1U << 28);   // ADC12EN

    /* 2. Exit deep power-down mode */
    *ADC_CR &= ~ADC_CR_DEEPPWD;

    /* 3. Enable ADC voltage regulator */
    *ADC_CR |= ADC_CR_ADVREGEN_0;

    /* 4. Wait >= 10 us (MANDATORY) */
    for (volatile int i = 0; i < 1000; i++);

    while (1);
}

